---
- name: Installs fleetDM on the Proxmox VM
  hosts: ADMIN_VLAN
  gather_facts: no
  become: true
  tasks:
    - name: Execute the script to install fleetDM
      ansible.builtin.shell: curl -s https://fleetdm.com/install.sh | sudo bash

    - name: Start the fleetDM service
      ansible.builtin.shell: sudo systemctl start fleet
