# vaultwarden-ingressroute.yaml
apiversion: traefik.io/v1alpha1
kind: ingressroute
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  entrypoints:
    - websecure
  routes:
  - match: host(`vaultwarden.local`)
    kind: rule
    services:
    - name: vaultwarden
      port: 80
  tls:
    secretname: vaultwarden-cert
