services:
  daemon:
    image: ghcr.io/scanopy/scanopy/daemon:latest
    container_name: scanopy-daemon-home-lan
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      - SCANOPY_SERVER_URL=http:/10.0.30.11:60072
      - SCANOPY_NETWORK_ID=6fa06238-184c-43b6-b318-8656dbd49c1c
      - SCANOPY_DAEMON_API_KEY=a0d4a0a5d62b4ba58d6b95fd9fe5a4f7
      - SCANOPY_USER_ID=10e17be7-3549-40fd-903a-eaa06ca2b60f
      - SCANOPY_NAME=k8s
      - SCANOPY_MODE=Push
    volumes:
      - daemon-config:/root/.config/daemon
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  daemon-config:
