---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey


title: Homelab

background:
  image: https://images.unsplash.com/photo-1687300172792-68a13c4e149a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1074
  blur: sm 
  saturate: 90
  brightness: 50 
  opacity: 50 
