apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm
  namespace: npm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npm
  template:
    metadata:
      labels:
        app: npm
    spec:
      containers:
        - name: npm
          image: jc21/nginx-proxy-manager:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: admin
              containerPort: 81

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: password

          volumeMounts:
            - name: npm-storage
              mountPath: /data
      volumes:
        - name: npm-storage
          persistentVolumeClaim:
            claimName: npm-data
