---
services:
  lab-dash:
      container_name: lab-dash
      image: ghcr.io/anthonygress/lab-dash:latest
      privileged: true
      ports:
        - 2022:2022
      environment:
        - SECRET=XX2E+Tw+0TN01nkJFoQ9F8y8qMWav6LTYU+7bV4S9AY=
      volumes:
        - ./sys:/sys:ro
        - ./config:/config
        - ./uploads:/app/public/uploads
        - /var/run/docker.sock:/var/run/docker.sock
      restart: unless-stopped
