---
- name: Enable vim bindings in bash
  hosts: test
  become: yes
  gather_facts: no
  vars:
    bashrc_entry: bind '"\C-l":"clear\n"'
  tasks:
    - name: Ensure vim mode is enabled in .bashrc
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        line: "{{ bashrc_entry }}"
        insertafter: EOF
        create: yes
